version: '3.9'

services: 
  #MongoDB service
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  #Node
  api:
    build: .
    ports: 
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_DB_URI: mongodb://mongodb:27017/book-management
      JWT_SECRET_KEY: bookmanagement
    depends_on:
      -  mongodb